[package]
name = "clearlog"
version = "0.1.0"
authors = ["GXHINF8OL4LO0IV\\Administrator <tijay830@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono="0.4.9"