[package]
name = "tcp"
version = "0.1.0"
authors = ["reison <tijay830@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std="1.4.0"
num_cpus="1.10.1"
threadpool="1.7.1"
simplelog = "0.7.3"
log="0.4.8"